branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: union-road-price-recommendations-dev
global:
  application_name: union-road-price-recommendations
  branch: null
  default_ec2_keyname: aws-eb-union-road
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: br-union-road
  repository: null
  sc: git
  workspace_type: Application
